/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    mavenLocal()
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("otterop:lang:0.2.0-SNAPSHOT")
    implementation("otterop:io:0.2.0-SNAPSHOT")
    // Use JUnit Jupiter for testing.
    testImplementation("otterop:test:0.2.0-SNAPSHOT")
}

tasks.withType<Jar>() {
    manifest.attributes["Main-Class"] = "example.sort.SortPure"
    configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("example.sort.SortPure")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
