#!/bin/sh
cat <<'EOF'
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 */
rootProject.name = "otterop-example-sort"

EOF
if [ "$OTTEROP_DEPENDENCIES" = "local" ]; then
cat <<'EOF'
includeBuild("otterop/java") {
    name = "otterop"
    dependencySubstitution {
        substitute(module("dev.otterop:lang")).using(project(":lang"))
        substitute(module("dev.otterop:io")).using(project(":io"))
        substitute(module("dev.otterop:test")).using(project(":test"))
    }
}
EOF
fi
