include otterop/lang/deps.mk
include otterop/io/deps.mk

EXAMPLE_QUICKSORT_QUICKSORT_OBJS:=example/quicksort/quicksort.o \
$(OTTEROP_LANG_ARRAY_OBJS) $(OTTEROP_LANG_STRING_OBJS) $(OTTEROP_IO_CONSOLE_OBJS)

EXAMPLE_QUICKSORT_LDFLAGS=$(OTTEROP_LANG_LDFLAGS) $(OTTEROP_IO_LDFLAGS)
EXAMPLE_QUICKSORT_LIBRARIES=$(OTTEROP_LANG_LIBRARIES) $(OTTEROP_IO_LIBRARIES)
EXAMPLE_QUICKSORT_INCLUDES=$(OTTEROP_LANG_INCLUDES) $(OTTEROP_IO_INCLUDES)
EXAMPLE_QUICKSORT_DEPENDENCIES=

example/quicksort/quicksort.o: $(OTTEROP_LANG_ARRAY_OBJS) $(OTTEROP_LANG_STRING_OBJS) $(OTTEROP_IO_CONSOLE_OBJS)
